[tool.pytest.ini_options]
# Tell pytest which folders contain tests
testpaths = [
    "Model-View-Controller/code-examples/python/tests",
    "contact_book_app/tests",
]
# Add your source code directories to Python's path
# This allows tests to find and import your application code
pythonpath = [
    "Model-View-Controller/code-examples/python",
    "contact_book_app/src",
]