name: Python Application CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11"] # Test against multiple Python versions

    steps:
    - name: Check out repository code
      uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-cov
        # This is the most important step:
        # It installs your project in "editable" mode so pytest can find it.
        pip install -e .

    - name: Run tests with pytest
      run: |
        # Specify the package to cover for more accurate reporting
        pytest --cov=contact_book_app --cov-report=xml