# .github/workflows/main-ci.yml
name: Python CI and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-cov codecov
          # This is the crucial step that was missing.
          # It installs your project in "editable" mode so pytest can find it.
          pip install -e .

      - name: Run tests and generate coverage report
        # The PYTHONPATH environment variable is no longer needed.
        # We specify the package to cover for more accurate reporting.
        run: pytest --cov=contact_book_app --cov-report=xml

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}