# .github/workflows/main-ci.yml
name: Python CI and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      # Updated installation step
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-cov codecov

      # Updated test step to generate coverage report
      - name: Run tests with pytest and coverage
        env:
          PYTHONPATH: Model-View-Controller/code-examples/python
        run: pytest --cov=./ --cov-report=xml

      # New step to upload coverage to Codecov
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
